apiVersion: v1
kind: Pod
metadata:
    name: web-server
    labels:
        app: web
spec:
    volumes:
    - name: web-pages
      emptyDir: {}

    containers:
    - name: server
      image: httpd:2.4
      ports:
        - containerPort: 80
      volumeMounts:
        - name: web-pages
          mountPath: /usr/local/apache2/htdocs/

    initContainers:
    - name: initializer
      image: alpine/git:v2.24.1
      env:
      - name: REPO_URL
        value: https://github.com/empovit/kubernetes-playground.git
      command: ['sh', '-c', 'git clone $(REPO_URL) /pages']  
      volumeMounts:
        - name: web-pages
          mountPath: /pages/
